# Generated by Django 4.2.15 on 2024-11-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequests',
            name='request_status',
            field=models.CharField(choices=[('D', 'D'), ('U', 'U'), ('P', 'P'), ('A', 'A')], default='Pending', max_length=20),
        ),
    ]
