# Generated by Django 4.2.15 on 2024-11-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_friendrequests_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequests',
            name='request_status',
            field=models.CharField(choices=[('P', 'P'), ('A', 'A'), ('D', 'D'), ('U', 'U')], default='Pending', max_length=20),
        ),
    ]
