# Generated by Django 5.1.1 on 2024-10-18 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_tournament_max_players'),
    ]

    operations = []
