# Generated by Django 5.1.1 on 2024-10-18 23:39

from django.db import migrations

def remove_duplicates(apps, schema_editor):
    TournamentPlayer = apps.get_model('tournament', 'TournamentPlayer')
    seen = set()
    duplicates = []

    # Parcourir toutes les instances de TournamentPlayer
    for tp in TournamentPlayer.objects.all():
        key = (tp.player_id, tp.tournament_id)
        if key in seen:
            duplicates.append(tp.id)  # Ajouter l'ID du doublon
        else:
            seen.add(key)

    # Supprimer les doublons
    if duplicates:
        TournamentPlayer.objects.filter(id__in=duplicates).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_alter_tournamentplayer_unique_together'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
    ]

