# Generated by Django 5.1.1 on 2024-10-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_alter_tournament_max_players'),
        ('tournament', '0006_remove_duplicates'),
    ]

    operations = [
    ]
